<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Shared.ApplicationLayer" Version="1.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Freelance.Identity.Domain\Freelance.Identity.Domain.csproj" />
    </ItemGroup>


</Project>
