otel.receiver.otlp "default" {
  grpc {
    endpoint = "0.0.0.0:4317"
  }

  http {
    endpoint = "0.0.0.0:4318"
  }

  output {
    metrics = [otel.processor.batch.default.input]
    logs    = [otel.processor.batch.default.input]
    traces  = [otel.processor.batch.default.input]
  }
}

otel.processor.batch "default" {
  output {
    metrics = [otel.exporter.prometheus.default.input]
    logs    = [otel.exporter.loki.default.input]
    traces  = [otel.exporter.otlp.tempo.input]
  }
}

otel.exporter.otlp "tempo" {
  client {
    endpoint = "tempo:9095"
    tls {
      insecure = true
    }
  }
}

otel.exporter.loki "default" {
  forward_to = [loki.write.default.receiver]
}

loki.write "default" {
  endpoint {
    url = "http://loki:3100/loki/api/v1/push"
  }
}

otel.exporter.prometheus "default" {
  forward_to = [prometheus.remote_write.default.receiver]
}

prometheus.remote_write "default" {
  endpoint {
    url = "http://prometheus:9090/api/v1/write"
  }
}