<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.0" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
        <PackageReference Include="Freelance.Shared.Api" Version="1.0.0" />
        <PackageReference Include="Freelance.Shared.Application" Version="1.0.0" />
        <PackageReference Include="Freelance.Shared.Domain" Version="1.0.1" />
        <PackageReference Include="Freelance.Shared.Infrastructure" Version="1.0.0" />
        <PackageReference Include="MediatR" Version="13.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Freelance.Identity.Application\Freelance.Identity.Application.csproj" />
        <ProjectReference Include="..\Freelance.Identity.Domain\Freelance.Identity.Domain.csproj" />
        <ProjectReference Include="..\Freelance.Identity.Infrastructure\Freelance.Identity.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>


    


</Project>
