<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<OutputType>Exe</OutputType>
	<UserSecretsId>8070f591-387f-4837-98e6-48a46d0ade58</UserSecretsId>
	<DockerfileContext>..\..</DockerfileContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
        <PackageReference Include="Shared.ApiLayer" Version="1.2.9" />
    </ItemGroup>


    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\Freelance.Identity.Application\Freelance.Identity.Application.csproj" />
      <ProjectReference Include="..\Freelance.Identity.Domain\Freelance.Identity.Domain.csproj" />
      <ProjectReference Include="..\Freelance.Identity.Infrastructure\Freelance.Identity.Infrastructure.csproj" />
    </ItemGroup>


    


</Project>
