<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Freelance.Shared.Domain">
            <HintPath>..\..\Freelance.Shared\Freelance.Shared.Domain\bin\Debug\net9.0\Freelance.Shared.Domain.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>  