<Project Sdk="Microsoft.NET.Sdk">


<PropertyGroup>
  <TargetFramework>net9.0</TargetFramework>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>enable</Nullable>
  <Version>1.0.0</Version>
  <Authors>ionut1912</Authors>
  <Company>FreelanceApp</Company>
  <PackageId>Freelance.Shared.Infrastructure</PackageId>
  <Description>Shared infrastructure layer for Freelance microservices</Description>
  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  <IncludeSymbols>true</IncludeSymbols>
  <IncludeSource>true</IncludeSource>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  <DocumentationFile>bin\Release\net9.0\Freelance.Shared.Infrastructure.xml</DocumentationFile>
</PropertyGroup>


    <ItemGroup>
      <PackageReference Include="Freelance.Shared.Domain" Version="1.0.1" />
      <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.3.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

</Project>
