<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Freelancer.UserProfiles.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="15.1.0"/>
        <PackageReference Include="FluentValidation" Version="12.1.0"/>
        <PackageReference Include="MediatR" Version="13.1.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Freelance.UserProfiles.Domain\Freelance.UserProfiles.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Freelance.Shared.Domain">
            <HintPath>..\..\Freelance.Shared\Freelance.Shared.Domain\bin\Debug\net9.0\Freelance.Shared.Domain.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
