<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
 <Version>1.0.0</Version>
    <Authors>ionut1912</Authors>
    <Company>FreelanceApp</Company>
    <PackageId>Freelance.Shared.Application</PackageId>
    <Description>Shared application layer for Freelance microservices</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  <DocumentationFile>bin\Release\net9.0\Freelance.Shared.Application.xml</DocumentationFile>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.0" />
      <PackageReference Include="Freelance.Shared.Domain" Version="1.0.1" />
      <PackageReference Include="MediatR" Version="13.1.0" />
    </ItemGroup>

</Project>
