<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
        <PackageReference Include="MediatR" Version="13.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Freelance.UserProfiles.Application\Freelance.UserProfiles.Application.csproj" />
      <ProjectReference Include="..\Freelance.UserProfiles.Domain\Freelance.UserProfiles.Domain.csproj" />
      <ProjectReference Include="..\Freelance.UserProfiles.Infrastructure\Freelance.UserProfiles.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Freelance.Shared.Application">
        <HintPath>..\..\Freelance.Shared\Freelance.Shared.Application\bin\Debug\net9.0\Freelance.Shared.Application.dll</HintPath>
      </Reference>
      <Reference Include="Freelance.Shared.Domain">
        <HintPath>..\..\Freelance.Shared\Freelance.Shared.Domain\bin\Debug\net9.0\Freelance.Shared.Domain.dll</HintPath>
      </Reference>
      <Reference Include="Frelance.Shared.Infrastructure">
        <HintPath>..\..\Freelance.Shared\Frelance.Shared.Infrastructure\bin\Debug\net9.0\Frelance.Shared.Infrastructure.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
