<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
  <TargetFramework>net9.0</TargetFramework>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>enable</Nullable>
  <Version>1.0.0</Version>
  <Authors>ionut1912</Authors>
  <Company>FreelanceApp</Company>
  <PackageId>Freelance.Shared.Domain</PackageId>
  <Description>Shared domain layer for Freelance microservices</Description>
  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  <IncludeSymbols>true</IncludeSymbols>
  <IncludeSource>true</IncludeSource>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  <DocumentationFile>bin\Release\net9.0\Freelance.Shared.Domain.xml</DocumentationFile>

  <!-- GitHub NuGet metadata -->
  <RepositoryUrl>https://github.com/ionut1912/freelance_api</RepositoryUrl>
  <RepositoryType>git</RepositoryType>
  <PackageProjectUrl>https://github.com/ionut1912/freelance_api</PackageProjectUrl>
  <PackageLicenseExpression>MIT</PackageLicenseExpression>
</PropertyGroup>
</Project>